'''
@Author: Samadhan Thube

@Date: 2024-08-28

@last modified by : Samadhan Thube

@last modified date : 2024-08-28
 
@Title : Numpy Library

'''

In [1]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

In [2]:
def list_to_numpy_array(original_list):
    """
    Description:
        Converts a list of numeric values into a one-dimensional NumPy array.
    
    Parameter:
        input_list (list): A list of numeric values.
        
    Return:
        numpy.ndarray: A one-dimensional NumPy array containing the numeric values from the input list.
    """
    return np.array(original_list)

def main():
    
    original_list = [12.23, 13.32, 100, 36.32]
    print("Original List:", original_list)
    
    numpy_array = list_to_numpy_array(original_list)
    print("One-dimensional numpy array:", numpy_array)

if __name__ == "__main__":
    main()

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
def create_matrix(start, end, shape):
    """
    Description:
        Creates a matrix with values in a specified range and shape.
    
    Parameters:
        start (int): The starting value of the range.
        end (int): The ending value of the range.
        shape (tuple): The desired shape of the matrix.
        
    Return:
        numpy.ndarray: A matrix with values ranging from start to end.
    """
    return np.arange(start, end + 1).reshape(shape)

def main():
    
    start_value = 2
    end_value = 10
    matrix_shape = (3, 3)
    
    matrix = create_matrix(start_value, end_value, matrix_shape)
    
    print("3x3 Matrix with values ranging from 2 to 10:")
    print(matrix)

if __name__ == "__main__":
    main()

3x3 Matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [4]:
def null_vector (size , index ,value):
    """
    Description:
        Creates a null vector of a given size and updates a specified index with a new value.
    
    Parameters:
        size (int): The size of the null vector.
        index (int): The index of the element to update.
        value (int): The new value to be set at the specified index.
        
    Return:
        numpy.ndarray: A null vector with an updated value at the specified index.
    """
    
    vector = np.zeros(size)
    
    vector[index] = value
    
    return vector

def main():
    
    size = 10
    index = 5
    value = 11
    
    print(null_vector(size,index,value))
    
if __name__ == "__main__":
    main()

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).

In [5]:
def reverse_array(original_array):
    """
    Description:
        Reverses the given NumPy array using np.flip.
    
    Parameter:
        original_array (numpy.ndarray): The array to be reversed.
        
    Return:
        numpy.ndarray: The reversed array.
    """
    return np.flip(original_array)

def main():

    original_array = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
    
    print("Original array:")
    print(original_array)
    
    reversed_array = reverse_array(original_array)
    
    print("Reverse array:")
    print(reversed_array)

if __name__ == "__main__":
    main()


Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [6]:
def create_border_array(size):
    """
    Description:
        Creates a 2D array with 1s on the border and 0s inside.
    
    Parameter:
        size (int): The size of the 2D square array.
        
    Return:
        numpy.ndarray: A 2D array with 1s on the border and 0s inside.
    """
    array = np.ones((size, size))
    
    array[1:-1, 1:-1] = 0
    
    return array

def main():
    
    size = 5
   
    original_array = np.ones((size, size))
    print("Original array:")
    print(original_array)
    
    bordered_array = create_border_array(size)
    print("\n1 on the border and 0 inside in the array:")
    print(bordered_array)

if __name__ == "__main__":
    main()

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
def add_zero_border(original_array):
    """
    Description:
        Adds a border of zeros around a 2D NumPy array.
    
    Parameter:
        array (numpy.ndarray): The original 2D array.
        
    Return:
        numpy.ndarray: A new 2D array with a border of zeros added.
    """
    bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)
    return bordered_array

def main():
    
    original_array = np.ones((3, 3))
    print("Original array:")
    print(original_array)
    
    
    bordered_array = add_zero_border(original_array)
    print("Array with a border of zeros:")
    print(bordered_array)


if __name__ == "__main__":
    main()

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array with a border of zeros:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [8]:
def checkerboard(original_array):
    """
    Description:
        Modifies a 2D NumPy array to have a checkerboard pattern.
    
    Parameter:
        original_array (numpy.ndarray): The original 2D array to modify.
        
    Return:
        numpy.ndarray: The modified 2D array with a checkerboard pattern.
    """

    original_array[1::2, ::2] = 1
    original_array[::2, 1::2] = 1
    
    return original_array

def main():
   
    original_array = np.zeros((8, 8), dtype=int)
    
    print("Original array:")
    print(original_array)
    
    checkerboard_array = checkerboard(original_array)
    
    print("\nCheckerboard pattern:")
    print(checkerboard_array)
    
if __name__ == "__main__":
    main()

Original array:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.

In [9]:
def convert_to_array(data):
    """
    Description:
        Converts a list or tuple into a NumPy array.
    
    Parameter:
        data (list or tuple): The input data to convert into a NumPy array.
        
    Return:
        numpy.ndarray: The converted NumPy array.
    """
    return np.array(data)

def main():
    
    sample_list = [1, 2, 3, 4, 5, 6, 7, 8]
    sample_tuple = ((8, 4, 6), (1, 2, 3))
  
    list_array = convert_to_array(sample_list)
    print("List to array:")
    print(list_array)

    tuple_array = convert_to_array(sample_tuple)
    print("\nTuple to array:")
    print(tuple_array)

if __name__ == "__main__":
    main()


List to array:
[1 2 3 4 5 6 7 8]

Tuple to array:
[[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.

In [10]:
def append_array(sample_array):
    """
    Description:
        Appends values ranging from 40 to 90 (with a step of 10) to the end of the given array.

    Parameter:
        sample_array (numpy.ndarray): The original array to which new values are appended.

    Return:
        numpy.ndarray: The updated array with appended values.
    """
    
    new_array = np.append(sample_array, np.arange(40, 100, 10))
    
    return new_array

def main():
    
    sample_array = np.array([10, 20, 30])
    
    print(append_array(sample_array))

if __name__ == "__main__":
    main()


[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.

In [11]:
def real_imaginary(original_array):
    """
    Description:
        Extracts the real and imaginary parts from a given array of complex numbers.

    Parameter:
        original_array (numpy.ndarray): An array of complex numbers.

    Return:
        tuple: Two numpy arrays containing the real and imaginary parts of the original array.
    """
    
    real_part = np.real(original_array)
    
    imaginary_part = np.imag(original_array)
    
    return real_part , imaginary_part
    
def main():
    
    original_array = np.array([1 + 0j, 0.70710678 + 0.70710678j])
    
    print("Original array:")
    print(original_array)
    
    real_part , imaginary_part = real_imaginary(original_array)
    print("\nReal part of the array:")
    print(real_part)
    
    print("\nImaginary part of the array:")
    print(imaginary_part)

if __name__ == "__main__":
    main()


Original array:
[1.        +0.j         0.70710678+0.70710678j]

Real part of the array:
[1.         0.70710678]

Imaginary part of the array:
[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.

In [12]:
def array_info(sample_array):
    """
    Description:
        Calculates the size of the array, the length of one array element in bytes, and the total bytes consumed by the array elements.

    Parameter:
        sample_array (numpy.ndarray): An array of elements.

    Return:
        tuple: Contains the size of the array, the length of one array element in bytes, and the total bytes consumed by the elements.
    """
    array_size = sample_array.size

    element_size = sample_array.itemsize

    total_bytes = sample_array.nbytes
    
    return array_size , element_size,total_bytes
    
def main():
    
    sample_array = np.array([1, 2, 3])
    
    array_size , element_size,total_bytes = array_info(sample_array)
    
    print("Size of the array:", array_size)
    print("Length of one array element in bytes:", element_size)
    print("Total bytes consumed by the elements of the array:", total_bytes)

if __name__ == "__main__":
    main()


Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


12. Write a Python program to find common values between two arrays.

In [13]:
def common_values(array1, array2):
    """
    Description:
        Finds the common values between two numpy arrays.

    Parameters:
        array1 (numpy.ndarray): The first input array.
        array2 (numpy.ndarray): The second input array.

    Returns:
        numpy.ndarray: An array containing the common values between the two input arrays.
    """
    common_values = np.intersect1d(array1, array2)
    return common_values

def main():
    
    array1 = np.array([0, 10, 20, 40, 60])
    array2 = np.array([10, 30, 40])
    
    print("Array1:", array1)
    print("Array2:", array2)
    
    common_values_array = common_values(array1, array2)
    print("\nCommon values between two arrays:")
    print(common_values_array)

if __name__ == "__main__":
    main()


Array1: [ 0 10 20 40 60]
Array2: [10 30 40]

Common values between two arrays:
[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.

In [14]:
def set_difference(array1, array2):
    """
    Description:
        Finds the set difference of two numpy arrays. Returns sorted, unique values in array1 that are not in array2.

    Parameters:
        array1 (numpy.ndarray): The first input array.
        array2 (numpy.ndarray): The second input array.

    Returns:
        numpy.ndarray: An array containing the set difference of the two input arrays.
    """
    
    difference = np.setdiff1d(array1, array2)
    return difference

def main():
   
    array1 = np.array([0, 10, 20, 40, 60, 80])
    array2 = np.array([10, 30, 40, 50, 70, 90])
    
    print("Array1:", array1)
    print("Array2:", array2)
    
    difference = set_difference(array1, array2)
    print("\nSet difference between two arrays:")
    print(difference)

if __name__ == "__main__":
    main()


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]

Set difference between two arrays:
[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.

In [15]:
def find_exclusive_or(array1, array2):
    """
    Description:
        Finds the set exclusive-or of two numpy arrays. Returns sorted, unique values that are in only one (not both) of the input arrays.

    Parameters:
        array1 (numpy.ndarray): The first input array.
        array2 (numpy.ndarray): The second input array.

    Returns:
        numpy.ndarray: An array containing the set exclusive-or of the two input arrays.
    """
    exclusive_or = np.setxor1d(array1, array2)
    return exclusive_or

def main():
   
    array1 = np.array([0, 10, 20, 40, 60, 80])
    array2 = np.array([10, 30, 40, 50, 70])
    
    print("Array1:", array1)
    print("Array2:", array2)
    
    exclusive_or = find_exclusive_or(array1, array2)
    print("\nUnique values that are in only one (not both) of the input arrays:")
    print(exclusive_or)

if __name__ == "__main__":
    main()


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]

Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.

In [16]:
def compare_arrays(array1, array2):
    """
    Description:
        Compares two numpy arrays element-wise using various comparison operators.

    Parameters:
        array1 (numpy.ndarray): The first input array.
        array2 (numpy.ndarray): The second input array.

    Returns:
        tuple: Contains the results of element-wise comparisons (>, >=, <, <=).
    """
    greater_than = array1 > array2
    greater_than_equal = array1 >= array2
    less_than = array1 < array2
    less_than_equal = array1 <= array2
    
    return greater_than, greater_than_equal, less_than, less_than_equal

def main():
   
    array_a = np.array([1, 2])
    array_b = np.array([4, 5])
  
    print("Array a:", array_a)
    print("Array b:", array_b)
 
    greater_than, greater_than_equal, less_than, less_than_equal = compare_arrays(array_a, array_b)
    
    print("\na > b")
    print(greater_than)
    
    print("\na >= b")
    print(greater_than_equal)
    
    print("\na < b")
    print(less_than)
    
    print("\na <= b")
    print(less_than_equal)

if __name__ == "__main__":
    main()


Array a: [1 2]
Array b: [4 5]

a > b
[False False]

a >= b
[False False]

a < b
[ True  True]

a <= b
[ True  True]


16. Write a Python program to save a NumPy array to a text file.

In [17]:
def array_to_file(array, file):
    """
    Description:
        Saves a NumPy array to a text file.

    Parameters:
        array (numpy.ndarray): The array to be saved.
        filename (str): The name of the text file to which the array will be saved.
        
    Return:
        None
    """
    
    np.savetxt(file, array) 

def main():
    
    array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    
    file = 'data.txt'
    
    array_to_file(array, file)
    
    print(f"Array has been saved to '{file}'")

if __name__ == "__main__":
    main()


Array has been saved to 'data.txt'


17. Write a Python program to create a contiguous flattened array.


In [18]:
def create_flattened_array(array):
    """
    Description:
        Flattens a multi-dimensional NumPy array into a contiguous one-dimensional array.

    Parameters:
        array (numpy.ndarray): The multi-dimensional array to be flattened.

    Returns:
        numpy.ndarray: A one-dimensional, contiguous flattened array.
    """

    flattened_array = array.ravel()
    return flattened_array

def main():
    
    original_array = np.array([[10, 20, 30], [20, 40, 50]])
 
    print("Original array:")
    print(original_array)

    flattened_array = create_flattened_array(original_array)

    print("\nNew flattened array:")
    print(flattened_array)

if __name__ == "__main__":
    main()


Original array:
[[10 20 30]
 [20 40 50]]

New flattened array:
[10 20 30 20 40 50]


18. Write a Python program to change the data type of an array.

In [19]:
import numpy as np

def change_dtype(array, new_dtype):
    """
    Description:
        Changes the data type of a NumPy array to the specified new data type.

    Parameters:
        array (numpy.ndarray): The array whose data type is to be changed.
        new_dtype (type): The new data type to which the array should be converted.

    Returns:
        numpy.ndarray: A new array with the specified data type.
    """
   
    new_array = array.astype(new_dtype)
    return new_array

def main():
 
    array = np.array([[2, 4, 6], [6, 8, 10]])

    print("Original array:")
    print(array)
    print("Data type of the array x is:", array.dtype)
    
    new_dtype = np.float64

    new_array = change_dtype(array,new_dtype )
  
    print("\nNew Type:", new_array.dtype)
    print(new_array)

if __name__ == "__main__":
    main()


Original array:
[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int64

New Type: float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


19. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.

In [20]:
def diagonal_array():
    """
    Description:
        Creates a 3-D array with ones on the diagonal and zeros elsewhere.
        The 2-D identity matrix is first created, and then it is expanded to
        a 3-D array by adding an extra dimension.
        
    Parameters:
        None

    Returns:
        numpy.ndarray: A 3-D array where each 2-D slice is an identity matrix.
    """
    
    array1 = np.eye(3)
    
    new_array = np.array(array1,ndmin=3)
    
    return new_array
    
def main():
    
    print(diagonal_array())
    
if __name__ == "__main__":
    main()

[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]]


20. Write a Python program to create an array which looks like below array.

In [21]:
def create_array():
    """
    Description:
        Creates a specific 2D array with incremental values as specified.
        
    Parameters:
        None

    Return:
        numpy.ndarray: A 2D array matching the expected output format.
    """
    array = np.zeros((4, 3))
    array[1, 0] = 1
    array[2, 0:2] = 1
    array[3, :] = 1

    return array

def main():
    
    print(create_array())

if __name__ == "__main__":
    main()


[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


21. Write a Python program to concatenate two 2-dimensional arrays.

In [22]:
def concat_array(sample_arrays):
    """
    Description:
        Concatenates two 2-dimensional arrays along the second axis (columns).

    Parameter:
        sample_arrays (list): A list containing two 3D numpy arrays.

    Return:
        numpy.ndarray: A 2D array resulting from the concatenation of arrays in the list.
    """
    new_array = np.concatenate(sample_arrays,1)
    
    return new_array

def main():
    sample_arrays = np.array([[[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]])

    print(concat_array(sample_arrays))
    
if __name__ == "__main__":
    main()

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


22. Write a Python program to make an array immutable (read-only).

In [23]:
import numpy as np

def immutable_array(sample_arr):
    """
    Description:
        Makes the given NumPy array read-only by setting its 'writeable' flag to False.

    Parameter:
        arr (numpy.ndarray): The NumPy array to be made read-only.

    Return:
        numpy.ndarray: The read-only version of the input array.
    """
    sample_arr.flags.writeable = False
    return sample_arr

def main():
   
    sample_arr = np.array([1, 2, 3, 4, 5])

    sample_arr= immutable_array(sample_arr)
    
    print("Test if the array is read-only:")
    
    try:
        sample_arr[0] = 1
    except ValueError as e:
        print(e)

if __name__ == "__main__":
    main()


Test if the array is read-only:
assignment destination is read-only


23. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.

In [24]:
def main():
    original_array = np.arange(12).reshape(3,4)
    new_array = original_array*3
    
    print(f"Original Array : \n{original_array}")
    print(f"New Array : \n{new_array}")
    
if __name__ == "__main__":
    main()

Original Array : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New Array : 
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


24. Write a Python program to convert a NumPy array into Python list structure.

In [25]:
def main():
    
    original_array = np.arange(6).reshape(3,2)
    print(original_array)

    list1 = original_array.tolist()
    print(f"Array to list : \n{list1}")
    
if __name__ == "__main__":
    main()

[[0 1]
 [2 3]
 [4 5]]
Array to list : 
[[0, 1], [2, 3], [4, 5]]


25. Write a Python program to convert a NumPy array into Python list structure.

In [26]:
def main():
    
    original_array = np.random.rand(10)  
    print(original_array)

    np.set_printoptions(3)
    
    print("\nPrint array values with precision 3:")
    print(original_array)

if __name__ == "__main__":
    main()


[0.45954478 0.71354159 0.60045126 0.88888426 0.77246023 0.89272094
 0.96166856 0.38176308 0.29140298 0.35873691]

Print array values with precision 3:
[0.46  0.714 0.6   0.889 0.772 0.893 0.962 0.382 0.291 0.359]


26. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.

In [27]:
def main():
    original_array =np.array([1.60000000e-10,1.60000000e+00,1.20000000e+03,2.35000000e-01])
    print(original_array)
    
    np.set_printoptions(3,suppress=True)
    
    print(f"suppress array : \n{original_array}")
    
if __name__ == "__main__":
    main()

[1.60e-10 1.60e+00 1.20e+03 2.35e-01]
suppress array : 
[   0.       1.6   1200.       0.235]


27.Write a Python program to how to add an extra column to an numpy array.

In [28]:
def add_column(arr, new_col):
    """
    Description:
        Adds a new column to the given NumPy array using np.column_stack().

    Parameters:
        arr (numpy.ndarray): The original 2D array.
        new_col (numpy.ndarray): The new column to be added.

    Return:
        numpy.ndarray: The array with the new column added.
    """
    return np.column_stack((arr, new_col))

def main():
  
    original_array = np.array([[10, 20, 30], [40, 50, 60]])
    
    print(original_array)
    
    new_column = np.array([100, 200])
   
    result_array = add_column(original_array, new_column)
 
    print("Array with new column added:")
    print(result_array)

if __name__ == "__main__":
    main()


[[10 20 30]
 [40 50 60]]
Array with new column added:
[[ 10  20  30 100]
 [ 40  50  60 200]]


28. Write a Python program to remove specific elements in a numpy array.

In [29]:
def main():
    
    original_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
    print("Original array:")
    print(original_array)
    new_array = np.delete(original_array,[0,3,4])
    
   
    print("\nDelete first, fourth and fifth elements:")
    print(new_array)

if __name__ == "__main__":
    main()

Original array:
[ 10  20  30  40  50  60  70  80  90 100]

Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]
